
import = ["~/.config/alacritty/colors.toml"]

working_directory = "None"
live_config_reload = true
ipc_socket = true          # unix only?

[env]
ALACRITTY = "1"

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 12, y = 12 }
dynamic_padding = true
decorations = "buttonless"
opacity = 1.0
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
resize_increments = true
option_as_alt = "OnlyLeft"              # "OnlyLeft" | "OnlyRight" | "Both" | "None"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "DemiBold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14.0
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false
bindings = []

# [hints]

[keyboard]
bindings = [
    { key = "Back", mods = "Command", chars = "\u0015" },    # CMD+Backspace > CTRL+U
    { key = "F", mods = "Command", action = "ReceiveChar" }, # unbind default CMD+f
    { key = "W", mods = "Command", action = "ReceiveChar" }, # unbind default CMD+w
]

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
