# chars = ansi escape sequences

# \u001b = ESC
# \x1B = escape character

# https://github.com/alacritty/alacritty/issues/474
# https://stackoverflow.com/questions/12382499/looking-for-altleftarrowkey-solution-in-zsh
# https://github.com/alacritty/alacritty/issues/7637

[window]
option_as_alt = "OnlyLeft"                  # "OnlyLeft" | "OnlyRight" | "Both" | "None"

[keyboard]
bindings = [
    { key = "Left", mods = "Alt", chars = "\u001bB" },  # ^[B
    { key = "Right", mods = "Alt", chars = "\u001bF" },  # ^[F
    { key = "Left", mods = "Command", chars = "\u001bOH" },
    { key = "Right", mods = "Command", chars = "\u001bOF" },
    { key = "Back", mods = "Command", chars = "\u0015" },
    { key = "F", mods = "Command", action = "ReceiveChar" }, # unbind default CMD+f
    { key = "W", mods = "Command", action = "ReceiveChar" }, # unbind default CMD+w
]

