# chars = ansi escape sequences

[keyboard]
bindings = [
    { key = "Left", mods = "Alt", chars = "\u001bB" },
    { key = "Right", mods = "Alt", chars = "\u001bF" },
    { key = "Left", mods = "Command", chars = "\u001bOH" },
    { key = "Right", mods = "Command", chars = "\u001bOF" },
    { key = "Back", mods = "Command", chars = "\u0015" },
    { key = "F", mods = "Command", action = "ReceiveChar" }, # unbind default CMD+f
    { key = "W", mods = "Command", action = "ReceiveChar" }, # unbind default CMD+w
]
