# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 5
truncate_to_repo = false
read_only = " "

[character]
# success_symbol = "['$'](green bold)"

[c]
symbol = " "

[conda]
symbol = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_metrics]
disabled = true
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = ""

[golang]
symbol = " "

[nodejs]
symbol = " "
version_format = "${major}.${minor}"

[package]
symbol = " "
disabled = true

[python]
version_format = "${major}.${minor}"
symbol = " "
style = "yellow bold"

[rust]
symbol = " "