# taps
tap "homebrew/bundle"
tap "oven-sh/bun"

# brews
brew "go"
brew "uv"
brew "rye"
brew "gcc"
brew "git"
brew "zsh"
brew "lua"
brew "mas"
brew "k9s"
brew "bun"
brew "stow"
brew "bash"
brew "fish"
brew "make"
brew "curl"
brew "wget"
brew "tmux"
brew "tilt"
brew "kind"
brew "helm"
brew "node"
brew "pnpm"
brew "deno"
brew "unzip"
brew "pyenv"
brew "poetry"
brew "neovim"
brew "docker"
brew "podman"
brew "colima"
brew "chezmoi"
brew "ansible"
brew "ripgrep"
brew "starship"
brew "opentofu"
brew "helmfile"
brew "coreutils"
brew "pre-commit"
brew "python@3.12"
brew "docker-buildx"
brew "kubernetes-cli"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-history-substring-search"

# casks
cask "zed"
cask "iina"
cask "bruno"
cask "lasso"
cask "iterm2"
cask "spotify"
cask "calibre"
cask "freetube"
cask "obsidian"
cask "1password"
cask "alacritty"
cask "raindropio"
cask "displaylink"
cask "proton-mail"
cask "sublime-text"
cask "transmission"
cask "proton-drive"
cask "eloston-chromium"
cask "librewolf", args: { no_quarantine: true }

# fonts
cask "font-meslo-lg"
cask "font-zed-mono"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"
cask "font-zed-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"

# app store apps
mas "rcmd", id: 1596283165
mas "Wipr", id: 1320666476
mas "Noir", id: 1592917505
mas "QuickShade", id: 931571202
mas "The Unarchiver", id: 425424353
mas "Save to Raindrop.io", id: 1549370672
mas "1Password for Safari", id: 1569813296
