" disable vi compatibility
set nocompatible

" file type detection
filetype on
filetype plugin on
filetype indent on

" syntax highlighting
syntax on

" line numbers
set number

" highlight current line
set cursorline

" shift width?
set shiftwidth=4

" tab width
set tabstop=4

" use spaces instead of tabs
set expandtab

" no backup files
set nobackup

" scroll below end of file
set scrolloff=10

" disable line wrap
set nowrap

" increment highlight search???
set incsearch

" case insensitive search
set ignorecase

" smart case sensitive search
set smartcase

" show command?
set showcmd

" show mode
set showmode

" hightlight matching words during search?
set showmatch

" highlight search results
set hlsearch

" increase command history (default 20)
set history=1000

" tab completion menu
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" cursor style:
" 1 = blinking block,        2 = steady block
" 3 = blinking underline,    4 = steady underline
" 5 = blinking vertical bar, 6 = steady vertical bar

" let &t_SI = "\e[5 q"   " cursor in insert mode
" let &t_EI = "\e[2 q"   " cursor in normal mode
" let &t_SR = "\e[3 q"   " cursor in replace mode
" let &t_ti .= "\e[2 q"  " cursor when vim starts
" let &t_te .= "\e[3 q"  " cursor when vim exits
