#!/usr/bin/env sh

SCRIPT="$HOME/.config/sketchybar/script.sh"

# customize bar
sketchybar --bar color=0x00000000 position=bottom y_offset=3 sticky=on topmost=off font_smoothing=on

# set item defaults
sketchybar --default \
    label.font="SF Pro:Regular:13.0" \
    label.color=0xfff5e0dc \
    icon.font="SF Pro:Semibold:14.0" \
    icon.color=0xfff5e0dc \
    padding_left=4 \
    padding_right=4 \
    label.padding_left=4 \
    label.padding_right=4 \
    icon.padding_left=4 \
    icon.padding_right=4

ITEM_STYLE="background.color=0xff000000 background.corner_radius=10 background.border_color=0xff555555 background.border_width=2 icon.padding_left=6 label.padding_right=8"

# add items
sketchybar \
    --add item week right --set week icon=􀆃 update_freq=3600 script="$SCRIPT" $ITEM_STYLE \
    --add item wifi right --set wifi script="$SCRIPT" $ITEM_STYLE --subscribe wifi wifi_change \
    --add item ip_address right --set ip_address update_freq=60 script="$SCRIPT" $ITEM_STYLE --subscribe wifi wifi_change

# --add item time right --set time icon=􀐬 update_freq=10 script="$SCRIPT" \
# --add item date right --set date icon=􀉉 update_freq=3600 script="$SCRIPT" \
# --add item battery right --set battery update_freq=15 script="$SCRIPT" \
# --add item volume right --set volume icon=􀊧 script="$SCRIPT" --subscribe volume volume_change \
# --add item brightness right --set brightness icon=􀆮 script="$SCRIPT" --subscribe brightness brightness_change \
# --add item app left --set app icon=􀣺 icon.padding_right=12 label.font="SF Pro:Semibold:14.0" script="$SCRIPT" --subscribe app front_app_switched

# force update
sketchybar --update
