#!/usr/bin/env sh

SCRIPTS="$HOME/.config/sketchybar/scripts"

sketchybar --bar \
    height=33 \
    position=top \
    color=0xff000000 \
    border_width=1 \
    border_color=0x40dcdcdc \
    sticky=on \
    topmost=off \
    margin=8 \
    y_offset=10 \
    corner_radius=5

sketchybar --default \
    label.font="SF Pro:Bold:14.0" \
    label.color=0xfff5e0dc \
    icon.font="SF Pro:Bold:14.0" \
    icon.color=0xfff5e0dc \
    padding_left=0 \
    padding_right=4 \
    label.padding_left=0 \
    label.padding_right=4 \
    icon.padding_left=0 \
    icon.padding_right=4

sketchybar \
    --add item clock right --set clock update_freq=10 script="$SCRIPTS/clock.sh" \
    --add item battery right --set battery icon=􀺶 update_freq=10 script="$SCRIPTS/battery.sh" \
    --add item app left --set app script="$SCRIPTS/event.sh" --subscribe app front_app_switched

sketchybar --update
